### PR TITLE
Address further questions in the PR

### PR DESCRIPTION
**Pull request by pfs**
I'll still top this PR up with the changes in the json file

### CODE REVIEW

**Comment by IzaakWN** [comment]
Looks good so far.

**Comment by pfs** [comment]
It runs - tested locally with Run 1726752058

**Comment by IzaakWN** [comment]
With which `hgcal-comm` branch / MR does this go?

**Comment by pfs** [comment]
it has to go with dev/rereco

**Comment by pfs** [comment]
Some comparisons in pedestal Relay 1726304466
- black prompt: reference pedestal file is something outdated from B27
- red re-reco v2: using latest jsons with cal pulse included

| DIGIs | RecHits |
| ----- | ----- |
| image | image |

Comparisons in CalPulse Relay 1726761905 (dac=3500 well in the TOT region for the injected channels). ADC (and corresponding hits are unchanged) but TOT not. Strange RecHit spectrum seems to indicate either an issue in the json or in the kernel.

| DIGIs | RecHits |
| ----- | ----- |
| image | image |
| image | image |

**Comment by pfs** [comment]
Ok there was indeed a swap in the kernel arguments. After the fix the RecHit  looks correct

image

**Comment by pfs** [comment]
From my side : ready to go :) I'm launching the v2 re-reco

**Comment by IzaakWN** [comment]
Thanks, @pfs. ~~If you didn't, can you run code checks before merging, please?~~ EDIT: Nevermind, I see you have a commit called "code checks"...

**Comment by pfs** [comment]
yes, last commit is from code-checks

**Comment by pfs** [comment]
Merging this one to update the main the PR.

**Pull request merged**
