### PR TITLE
Implement suggestions for CMSSW_14_1_X PR #45665

### PR DESCRIPTION
**Pull request by IzaakWN**
[Work in progress.]

Implement suggestions by @makortel in PR https://github.com/cms-sw/cmssw/pull/45665 to official CMSSW:
* Replace `enum` with `namespace` & `constexpr uint{8,16,32}_t` in [`DataFormats/HGCalDigi/interface/HGCalRawDataDefinitions.h`](https://github.com/CMS-HGCAL/cmssw/blob/dev/hackathon_base_CMSSW_14_1_X/DataFormats/HGCalDigi/interface/HGCalRawDataDefinitions.h).
* Remove `_t` postfix from `HGCalFEDReadoutSequence_t`, `HGCalROCConfig_t`, `HGCalECONDConfig_t`, `HGCalFedConfig_t` structs.
* Remove redundant comments.
* Move includes from [`RecoLocalCalo/HGCalRecAlgos/interface/alpaka/HGCalRecHitCalibrationAlgorithms.h`](https://github.com/CMS-HGCAL/cmssw/blob/dev/hackathon_base_CMSSW_14_1_X/RecoLocalCalo/HGCalRecAlgos/interface/alpaka/HGCalRecHitCalibrationAlgorithms.h) to [`RecoLocalCalo/HGCalRecAlgos/plugins/alpaka/HGCalRecHitCalibrationAlgorithms.dev.cc`](https://github.com/CMS-HGCAL/cmssw/blob/dev/hackathon_base_CMSSW_14_1_X/RecoLocalCalo/HGCalRecAlgos/plugins/alpaka/HGCalRecHitCalibrationAlgorithms.dev.cc).
* Remove trailing `_` from function arguments `n_blocks_` & `n_threads_`, and add to private data members.
* Code checks & formats from `scram build code-checks` or `scram build code-format`.
* ...

Needs to be run together with [`hgcal-dpg/hgcal-comm!45`](https://gitlab.cern.ch/hgcal-dpg/hgcal-comm/-/merge_requests/45).

### CODE REVIEW

**Comment by IzaakWN** [comment]
@yulunmiao & @hqucms, can you have a look at specifically the changes to the enumeration/constants, please?

Following [Matti's comments](https://github.com/cms-sw/cmssw/pull/45665#discussion_r1708019766), I changed the enumerators
```cpp
 enum ECONDFlag {
     BITT_POS = 0,
     BITM_POS = 1,
     EBO_POS = 2,
     EBO_MASK = 0b11,
     HT_POS = 4,
     HT_MASK = 0b11,
     BITE_POS = 6,
     BITS_POS = 7
   };
```
to `constexpr uint8_t` in the following way.
```cpp
  namespace ECONDFlag {
    constexpr uint8_t BITT_POS = 0, BITM_POS = 1, EBO_POS = 2, EBO_MASK = 0b11, HT_POS = 4, HT_MASK = 0b11,
                      BITE_POS = 6, BITS_POS = 7;
  }
```
(Unfortunately, the CMSSW code formatting converts the line breakes after commas to a single wrapped line as above, which is a bit ugly. Alternatively, we can write each constant as `constexpr uint8_t ... = ...;`.)

Choices of data types for the others are as follows:
```cpp
namespace hgcal {
  namespace econd {
    namespace ToTStatus {
      constexpr uint8_t ZeroSuppressed = 0x0, ...;
    }  // namespace ToTStatus
  }    // namespace econd

  namespace backend {
    namespace ECONDPacketStatus {
      constexpr uint8_t Normal = 0x0, ...;
    }  // namespace ECONDPacketStatus
  }    // namespace backend

  namespace ECOND_FRAME {
    constexpr uint32_t HEADER_POS = 23, ...;
  }  // namespace ECOND_FRAME

  namespace BACKEND_FRAME {
    constexpr uint32_t CAPTUREBLOCK_RESERVED_MASK = 0x7f, ...;
  }  // namespace BACKEND_FRAME

  namespace DIGI_FLAG {
    constexpr uint16_t
        FULL_READOUT = 0x0000, ...;
  }  // namespace DIGI_FLAG

}  // namespace hgcal
```

**Comment by yulunmiao** [comment]
Hi @IzaakWN, thank you for making the changes, I think the changes look good to me

**Review by pfs — APPROVED** [review]
All looks reasonable to me, thanks for implementing!

**Comment by IzaakWN** [comment]
Tested with
```shell
ssh lxplus9
source /cvmfs/cms.cern.ch/cmsset_default.sh

# install
export SCRAM_ARCH="el9_amd64_gcc12"
cmsrel CMSSW_14_1_0_pre4
cd CMSSW_14_1_0_pre4/src/
cmsenv

# checkout our development branch
git cms-merge-topic -u CMS-HGCAL:dev/CMSSW_14_1_X_PR_suggestions

# load external tools & data
git clone https://gitlab.cern.ch/hgcal-dpg/hgcal-comm.git HGCalCommissioning
git fetch origin CMSSW_14_1_X_PR_suggestions
git checkout CMSSW_14_1_X_PR_suggestions

# compile
scram b -j 10

# test that things are up and running (run unit tests)
scram b runtests

# if debug information is needed, instead of `scram b -j 10`, do
#USER_CXXFLAGS=-DEDM_ML_DEBUG scram b -j 10

cmsRun $CMSSW_BASE/src/HGCalCommissioning/SystemTestEventFilters/test/test_raw2reco.py charMode=0 dqmOnly=True prescale=100 maxEvents=5000 output=output_RunRUN.root inputFiles=/eos/cms/store/group/dpg_hgcal/tb_hgcal/2024/BeamTestAug/HgcalBeamtestAug2024/Relay1722965128/Run1722965131_Link1_File000000000[01].bin
```

**Pull request merged**
