### PR TITLE
Fix 64b padding of capture blocks

### PR DESCRIPTION
**Pull request by pfs**
The original picture we have been using as reference (see below) is not correct.
The additional 64b word used to pad the data of the capture blocks is only added, if needed, for the very last capture block in a SLink.

image

Some test cases  (alternates ZS and NZS events which leads sometimes to padding being needed):

* Input file without corruption: `cmsRun HGCalCommissioning/Configuration/test/step_RAW2DIGI.py run=1725175474 lumi=35 era=TB2024/v2 files=/eos/cms/store/group/dpg_hgcal/tb_hgcal/2024/hgcalrd/debug/Run1725175474_Link1_File0000000034.bin inputTrigFiles=/eos/cms/store/group/dpg_hgcal/tb_hgcal/2024/hgcalrd/debug/Run1725175474_Link0_File0000000034.bin yamls="{}"`

* input file with event corruption (usually CB header is missing): `cmsRun HGCalCommissioning/Configuration/test/step_RAW2DIGI.py run=1725175474 lumi=35 era=TB2024/v2 files=/eos/cms/store/group/dpg_hgcal/tb_hgcal/2024/hgcalrd/debug/Run1725175886_Link1_File0000000024.bin inputTrigFiles=/eos/cms/store/group/dpg_hgcal/tb_hgcal/2024/hgcalrd/debug/Run1725175886_Link0_File0000000024.bin yamls="{}"`
will crash with 
```
----- Begin Fatal Exception 10-Sep-2024 16:31:16 CEST-----------------------
An exception of category 'CorruptData' occurred while
   [0] Processing  Event run: 1725175474 lumi: 35 event: 24000012 stream: 0
   [1] Running path 'p'
   [2] Calling method for module HGCalRawToDigi/'hgcalDigis'
Exception Message:
Expected a capture block header at word 2/0x2 (reserved word: 0x7f), got 0x55 from 0xaa0290bdb5738cd6.
----- End Fatal Exception -------------------------------------------------
```

Note: the second example is not necessarily relevant for this PR it's just a test case to implement a passthrough in order not to block the run a the first event where this happens.

### CODE REVIEW

**Comment by yulunmiao** [comment]
Looks very good to me, please merge now, so I can develop capture block flags and S-Link flags based on this PR

**Comment by yulunmiao** [comment]
In 6e33892, I fix all the remaining `throw` to `return`, no the code won't stop at the first event with error

**Comment by IzaakWN** [comment]
Hi @yulunmiao, do we need to convert _all_ exceptions to returns, and not just the ones the skip the known issue with the dropped S-link packets (see Paul's presentation in https://indico.cern.ch/event/1454516/contributions/6123447/attachments/2923617/5131968/240909.pdf)? 

Also, I think it would still be useful to print out the old error message as just a warning, also saying the event is skipped (due to corrupted data).

**Comment by pfs** [comment]
Hi @yulunmiao after a check of a more recent run I propose to move the check of the padding word upstream in the code.

**Comment by yulunmiao** [comment]
Hi @pfs, reading the code, I think the reason why the end of thing won't work is because the number of capture blocks per S-Link is changed, either because the recent run get a different set up, or due to some crash. 
If it's the former, and we are foreseeing different S-Links would contain different number of CBs, a better way is to change the this line https://github.com/CMS-HGCAL/cmssw/blob/9c0c390ef8d4b384a0d772c7fb80b0707df81960/EventFilter/HGCalRawToDigi/src/HGCalUnpacker.cc#L81 to a S-Link based one, like we did here for number of eRx subpackets per ECON packet:https://github.com/CMS-HGCAL/cmssw/blob/9c0c390ef8d4b384a0d772c7fb80b0707df81960/EventFilter/HGCalRawToDigi/src/HGCalUnpacker.cc#L190
If it's the latter, it's actually a crash so we shall raise exception so keep the way it is now would be good.

**Comment by pfs** [comment]
Hi Yulun,
the system is the same but it's a crash. The runs alternate ZS and NZS events so the size varies significantly and sometimes padding is needed, sometimes not.
The loop condition
```
captureblockIdx < HGCalMappingModuleIndexer::maxCBperFED_ && ptr < trailer - 2; 
```
is not enough to signal that unpacking can finish in case 64b padding was used
* `ptr<trailer-2` will be true
* `HGCalMappingModuleIndexer::maxCBperFED_=10` but there are only 2 CB currently

The solution proposed will check if the next CB header is a 0x0 word and if there is 1 words to the expected start of the trailer. This is not very elegant but it's legitimate as this what is behavior of the BE.

Of course another solution would be to use the number of CB expected for each FED. This needs a change in the `HGCalMappingModuleIndexer` to store this information. It's possible.

In any case, in my opinion, this is not a case to "throw exception". It is expected as behavior, it was just poorly documented. We didn't notice this last year because everything was in the same capture block and the code was written slightly different (we were lucky somehow).

**Comment by yulunmiao** [comment]
In commit [b956210](https://github.com/CMS-HGCAL/cmssw/pull/147/commits/b95621068fd9af1f014d3462a5ea37a433f78de4), I changed all to specific return values

In commit [3775d54](https://github.com/CMS-HGCAL/cmssw/pull/147/commits/3775d54bf4c4c5742d6ee1d8a1894de071408276), I optimized the producer a bit

**Pull request merged**
